### ISSUE TITLE
Some suggestions.

### ISSUE THREAD

**Issue by Aleck85** [mzino/chrome-messenger-notifications#2]
1. It would be great to make the options like in Messenger + Facebook Notifications. When I clicking on the icon I want to go to the FB main page if I don't have any messages, and to the messager page if I have it.
2. For me the icon itself is not so good. Please make something in classic FB style. 
![social-facebook-icon](https://cloud.githubusercontent.com/assets/5072865/14214839/e5c6bf1c-f847-11e5-9bb6-a659bd76ea21.png)

**Comment by mzino** [comment]
1) I modded this extension to stay completely out of facebook.com and to use only messenger.com, so I won't add such an option. But you're free to fork and add it yourself: you just need to add a new variable to background.js

`var host2='www.facebook.com';`

and then edit the `openPage()` function including the new `host2` in the else:

`if(counter>0)`
`	openUrl(protocol+'://'+host+'/'+pathNew);`
`else`
`	openUrl(protocol+'://'+host2+'/'+pathZero);`

and it should work as you expect.

2) Same reason as before, this is a Messenger oriented extension, so it needs a Messenger icon.
